apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hetzner-object-storage
  namespace: backup-system
  labels:
    app: external-secrets
    component: s3-credentials
    plane: data
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: hetzner-vault
    kind: ClusterSecretStore
  target:
    name: hetzner-object-storage
    creationPolicy: Owner
  data:
  - secretKey: access_key
    remoteRef:
      key: hetzner-object-storage
      property: access_key
  - secretKey: secret_key
    remoteRef:
      key: hetzner-object-storage
      property: secret_key
  - secretKey: endpoint
    remoteRef:
      key: hetzner-object-storage
      property: endpoint
  - secretKey: region
    remoteRef:
      key: hetzner-object-storage
      property: region
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-app-user
  namespace: backup-system
  labels:
    app: external-secrets
    component: postgres-credentials
    plane: data
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: hetzner-vault
    kind: ClusterSecretStore
  target:
    name: postgres-app-user
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: postgres-app-user
      property: username
  - secretKey: password
    remoteRef:
      key: postgres-app-user
      property: password
  - secretKey: dbname
    remoteRef:
      key: postgres-app-user
      property: database
---
apiVersion: v1
kind: Secret
metadata:
  name: hetzner-object-storage
  namespace: backup-system
  labels:
    app: external-secrets
    component: s3-credentials
    plane: data
data:
  access_key: ""
  secret_key: ""
  endpoint: "aHR0cHM6Ly9mc24xLnlvdXItb2JqZWN0c3RvcmFnZS5jb20="
  region: "ZnNuMQ=="
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-app-user
  namespace: backup-system
  labels:
    app: external-secrets
    component: postgres-credentials
    plane: data
data:
  username: ""
  password: ""
  dbname: ""
