apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nats-jetstream-pvc
  namespace: data-plane
  labels:
    app: nats
    component: jetstream-storage
spec:
  storageClassName: hcloud-volumes
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi