apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: control-plane-appset
  namespace: dip-control-infra
spec:
  generators:
    - git:
        repoURL: https://github.com/gesseld/vps-cluster.git
        revision: master
        directories:
          - path: planes/phase-cp*
          - path: planes/phase-op*
    
  template:
    metadata:
      name: '{{path.basename}}'
      namespace: dip-control-infra
      labels:
        plane: control-infra
    
    spec:
      project: default
      
      source:
        repoURL: https://github.com/gesseld/vps-cluster.git
        targetRevision: master
        path: '{{path}}'
      
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
          allowEmpty: false
        
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
          - RespectIgnoreDifferences=true
        
        retry:
          limit: 3
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 60s