apiVersion: v1
kind: Service
metadata:
  name: temporal-frontend-lb
  namespace: data-plane
  labels:
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: temporal
    app.kubernetes.io/name: temporal
spec:
  type: LoadBalancer
  ports:
  - name: grpc
    port: 7233
    targetPort: 7233
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  selector:
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: temporal
    app.kubernetes.io/name: temporal