global:
  membership:
    broadcastAddress: "0.0.0.0"
  metrics:
    prometheus:
      listenAddress: "0.0.0.0:9090"
      handlerPath: "/metrics"
  pprof:
    port: 7933

persistence:
  defaultStore: "postgres"
  visibilityStore: "postgres_visibility"
  numHistoryShards: 512

  datastores:
    postgres:
      sql:
        pluginName: "postgres12"
        databaseName: "temporal"
        connectAddr: "${POSTGRES_SEEDS}:5432"
        connectProtocol: "tcp"
        user: "${POSTGRES_USER}"
        password: "${POSTGRES_PWD}"
        maxConns: 20
        maxIdleConns: 20
        maxConnLifetime: "1h"

    postgres_visibility:
      sql:
        pluginName: "postgres12"
        databaseName: "temporal_visibility"
        connectAddr: "${POSTGRES_SEEDS}:5432"
        connectProtocol: "tcp"
        user: "${POSTGRES_USER}"
        password: "${POSTGRES_PWD}"
        maxConns: 20
        maxIdleConns: 20
        maxConnLifetime: "1h"

clusterMetadata:
  enableGlobalNamespace: false
  failoverVersionIncrement: 10
  masterClusterName: "active"
  currentClusterName: "active"
  clusterInformation:
    active:
      enabled: true
      initialFailoverVersion: 0
      rpcAddress: "127.0.0.1:7233"
      httpAddress: "127.0.0.1:7400"

services:
  frontend:
    rpc:
      grpcPort: 7233
      membershipPort: 6933
      bindOnLocalHost: false
    publicClient:
      hostPort: "0.0.0.0:7233"

  history:
    rpc:
      grpcPort: 7234
      membershipPort: 6934
      bindOnLocalHost: false

  matching:
    rpc:
      grpcPort: 7235
      membershipPort: 6935
      bindOnLocalHost: false

  internal-frontend:
    rpc:
      grpcPort: 7236
      membershipPort: 6936
      bindOnLocalHost: false

  internal-history:
    rpc:
      grpcPort: 7237
      membershipPort: 6937
      bindOnLocalHost: false

  internal-matching:
    rpc:
      grpcPort: 7238
      membershipPort: 6938
      bindOnLocalHost: false

archival:
  history:
    state: "disabled"
    enableRead: false
  visibility:
    state: "disabled"
    enableRead: false

namespace:
  default:
    retention: "72h"

log:
  stdout: true
  level: "info"
  format: "json"

dynamicConfigClient:
  filepath: "/etc/temporal/config/dynamicconfig.yaml"