server:
  enabled: true

  image:
    repository: temporalio/server
    tag: 1.30.4

  nodeSelector:
    kubernetes.io/hostname: k3s-w-1
  frontend:
    replicaCount: 1
    podLabels:
      plane: control
      tenant: temporal
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
      limits:
        cpu: 300m
        memory: 512Mi

  history:
    replicaCount: 1
    podLabels:
      plane: control
      tenant: temporal
    resources:
      requests:
        cpu: 400m
        memory: 512Mi
      limits:
        cpu: 750m
        memory: 1Gi

  matching:
    replicaCount: 1
    podLabels:
      plane: control
      tenant: temporal
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
      limits:
        cpu: 300m
        memory: 512Mi

  worker:
    replicaCount: 1
    podLabels:
      plane: control
      tenant: temporal
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 150m
        memory: 256Mi

  config:
    persistence:
      defaultStore: default
      visibilityStore: visibility
      numHistoryShards: 512

      default:
        driver: sql
        sql:
          driver: postgres12
          host: postgresql-primary.data-plane.svc.cluster.local
          port: 5432
          database: temporal
          user: temporal
          password: temporal_password
          maxConns: 20
          maxConnLifetime: "5m"
          maxIdleConns: 5

      visibility:
        driver: sql
        sql:
          driver: postgres12
          host: postgresql-primary.data-plane.svc.cluster.local
          port: 5432
          database: temporal_visibility
          user: temporal
          password: temporal_password
          maxConns: 20
          maxConnLifetime: "5m"
          maxIdleConns: 5

  metrics:
    enabled: false

web:
  enabled: true
  replicaCount: 1
  podLabels:
    plane: control
    tenant: temporal
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

admintools:
  enabled: true
  podLabels:
    plane: control
    tenant: temporal
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

prometheus:
  enabled: false

alertmanager:
  enabled: false

grafana:
  enabled: false

elasticsearch:
  enabled: false

cassandra:
  enabled: false

kafka:
  enabled: false

influxdb:
  enabled: false

schema:
  enabled: false
  podLabels:
    plane: control
    tenant: temporal
  nodeSelector:
    kubernetes.io/hostname: k3s-w-1

commonLabels:
  plane: control
  tenant: temporal

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000

securityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL