server:
  enabled: true
  image:
    repository: temporalio/server
    tag: 1.30.4
  replicaCount: 1
  
  config:
    logLevel: "info"
    persistence:
      numHistoryShards: 10
      defaultStore: default
      visibilityStore: visibility
      manageSchema: true
      datastores:
        default:
          sql:
            pluginName: postgres12
            driverName: postgres12
            connectProtocol: tcp
            databaseName: temporal
            connectAddr: "postgresql-primary:5432"
            user: temporal
            password: "password"
            createDatabase: false
            manageSchema: true
        visibility:
          sql:
            pluginName: postgres12
            driverName: postgres12
            connectProtocol: tcp
            databaseName: temporal_visibility
            connectAddr: "postgresql-primary:5432"
            user: temporal
            password: "password"
            createDatabase: false
            manageSchema: true

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi

  serviceAccount:
    create: true
    name: temporal-server

  podLabels:
    plane: data
    tenant: temporal-tenant

  securityContext:
    runAsUser: 1000
    fsGroup: 1000
