apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nvme-waitfirst
provisioner: rke.csi.rancher.io
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  csi.storage.k8s.io/fstype: ext4
