apiVersion: v1
kind: ServiceAccount
metadata:
  name: temporal-server
  namespace: control-plane
  labels:
    app: temporal
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: temporal-server
  namespace: control-plane
  labels:
    app: temporal
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: temporal-server
  namespace: control-plane
  labels:
    app: temporal
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: temporal-server
subjects:
- kind: ServiceAccount
  name: temporal-server
  namespace: control-plane
