apiVersion: v1
kind: Secret
metadata:
  name: temporal-postgres-creds
  namespace: control-plane
  labels:
    app: temporal
    component: credentials
type: Opaque
stringData:
  username: "temporal"
  password: "temporal_password"
  host: "postgresql.data-plane.svc.cluster.local"
  database: "temporal_visibility"