apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: {{ .Namespace }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  # No rules = deny all by default
